### ISSUE TITLE
subdocument redirect causes redirect of entire document

### ISSUE THREAD

**Issue by practik** [tumpio/requestcontrol#103]
### Steps to reproduce the problem
* Create redirect rule with host = `www.youtube.com`, path = `*`, types = document and subdocument, action = `[hostname=www.invidio.us]`
* Navigate to any page with an embedded YouTube video, such as `https://genius.com/videos/How-mariah-carey-s-obsessed-became-a-tiktok-meme`
* Entire page will redirect – in this case, to `https://www.invidio.us/embed/H1Yt0xJKDY8`

This just started for me yesterday, so I think it must be a regression since 1.12.4.

**Comment by tumpio** [comment]
Hi @practik! Can you test if I got it fixed in this unlisted beta version:
https://addons.mozilla.org/firefox/downloads/file/3376932/request_control-1.13.1a-an+fx.xpi

**Comment by practik** [comment]
Hi @tumpio! Hmm … 1.13.1 looks like a partial fix. YouTube embeds seem to be working correctly now (i.e., not redirecting the whole page). But I can still reproduce the problem with a filter rule, like this:
* Create filter rule with host = All URLs, types = document and subdocument, action = trim `utm_*`
(This is the `utm` default rule that comes preinstalled with RC, expanded to include subdocuments as well as documents.)
* Navigate to `https://garage.vice.com/en_us/article/mbmjpv/arden-surdam-photography`, which contains a link including a `utm_*` parameter
* Entire page will redirect to the linked URL.

**Comment by tumpio** [comment]
Fixed it by adding it as an option in 1.14.0 :)
