### ISSUE TITLE
Long list of hosts doesn't fit in "Host" field

### ISSUE THREAD

**Issue by anewuser** [tumpio/requestcontrol#104]
This list of hosts has 70 items:

![requestcontrol](https://user-images.githubusercontent.com/6733770/63215935-1225ae00-c104-11e9-90eb-2508b503dd8c.png)

Request Control 1.13.1
Firefox stable

**Comment by tumpio** [comment]
Fixed in 1.13.2, thanks for reporting!

**Comment by anewuser** [comment]
@tumpio I'm still having that problem with this:

[request-control-rules.txt](https://github.com/tumpio/requestcontrol/files/3518053/request-control-rules.txt)

**Comment by tumpio** [comment]
Should be fixed in 1.13.3

**Comment by anewuser** [comment]
Thanks for looking into it.
